DROP DATABASE IF EXISTS SUPERSCAN;
CREATE DATABASE SUPERSCAN;
USE SUPERSCAN;

CREATE TABLE USER (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	rol INT,
	name VARCHAR(100),
	password VARCHAR(100),
	email VARCHAR(100)
);
	
CREATE TABLE item (
	id INT PRIMARY KEY NOT NULL,
	NAME VARCHAR(200)
);

CREATE TABLE SUPERMARKET (
	id INT PRIMARY KEY NOT NULL,
	name VARCHAR(100)
);

CREATE TABLE CATEGORY (
	id INT PRIMARY KEY NOT NULL,
	name VARCHAR(100)
);

CREATE TABLE COMPARE (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	id_item INT,
	id_supermarket INT,
	id_category INT,
	FOREIGN KEY (id_item) REFERENCES item (id),
	FOREIGN KEY (id_supermarket) REFERENCES supermarket (id),
	FOREIGN KEY (id_category) REFERENCES category (id)
);

CREATE TABLE CART (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	id_user INT,
	id_item INT,
	FOREIGN KEY (id_user) REFERENCES user (id),
	FOREIGN KEY (id_item) REFERENCES item (id)
);